### ISSUE TITLE
An error will occur in "library mode"

### ISSUE THREAD

**Issue by 4tj** [z0ffy/vite-plugin-bundle-obfuscator#121]
When I use "[library mode](https://vite.dev/guide/build.html#library-mode)" to package, an error occurs:
```
error during build:
Invalid value for option "output.manualChunks" - this option is not supported for "output.inlineDynamicImports".
```

vite.config.ts:
```
const minimizeObfuscatorConfig = {
  autoExcludeNodeModules: true,
  threadPool: true,
};

export default {
  build: {
    lib: {
      entry: "src/lib/mylib.ts",
      name: "MyLib",
      fileName: "my-lib",
    },
  },
  plugins: [vitePluginBundleObfuscator(minimizeObfuscatorConfig)],
} satisfies UserConfig;
```

**Comment by z0ffy** [comment]
> When I use "[library mode](https://vite.dev/guide/build.html#library-mode)" to package, an error occurs:
> 
> ```
> error during build:
> Invalid value for option "output.manualChunks" - this option is not supported for "output.inlineDynamicImports".
> ```
> 
> vite.config.ts:
> 
> ```
> const minimizeObfuscatorConfig = {
>   autoExcludeNodeModules: true,
>   threadPool: true,
> };
> 
> export default {
>   build: {
>     lib: {
>       entry: "src/lib/mylib.ts",
>       name: "MyLib",
>       fileName: "my-lib",
>     },
>   },
>   plugins: [vitePluginBundleObfuscator(minimizeObfuscatorConfig)],
> } satisfies UserConfig;
> ```

I have received the feedback and will reply as soon as possible.

**Comment by z0ffy** [comment]
Setting autoExcludeNodeModules to false can resolve the error, but obfuscation will not be performed. I will need some time to handle this.

**Comment by khanakia** [comment]
@z0ffy not working
```ts
import { defineConfig } from 'vite';
import { resolve } from 'path';
import vitePluginBundleObfuscator from 'vite-plugin-bundle-obfuscator';
const minimizeObfuscatorConfig = {
  autoExcludeNodeModules: true,
  threadPool: true,
};

export default defineConfig({
  build: {

    lib: {
      entry: resolve(__dirname, 'src/main.ts'),
      formats: ['umd'],
      name: 'test',
    },
    rollupOptions: {},
  },

  plugins: [
    vitePluginBundleObfuscator(minimizeObfuscatorConfig),
  ],
});

```


```sh
error during build:
Invalid value for option "output.manualChunks" - this option is not supported for "output.inlineDynamicImports".
    at getRollupError (file:///Volumes/D/khanakia/Downloads/thewildai_chatbot_bubble/node_modules/.pnpm/rollup@4.34.1/node_modules/rollup/dist/es/shared/parseAst.js:396:41)
    at error (file:///Volumes/D/khanakia/Downloads/thewildai_chatbot_bubble/node_modules/.pnpm/rollup@4.34.1/node_modules/rollup/dist/es/shared/parseAst.js:392:42)
    at getManualChunks (file:///Volumes/D/khanakia/Downloads/thewildai_chatbot_bubble/node_modules/.pnpm/rollup@4.34.1/node_modules/rollup/dist/es/shared/node-entry.js:22648:20)
    at normalizeOutputOptions (file:///Volumes/D/khanakia/Downloads/thewildai_chatbot_bubble/node_modules/.pnpm/rollup@4.34.1/node_modules/rollup/dist/es/shared/node-entry.js:22436:23)
    at getOutputOptions (file:///Volumes/D/khanakia/Downloads/thewildai_chatbot_bubble/node_modules/.pnpm/rollup@4.34.1/node_modules/rollup/dist/es/shared/node-entry.js:22806:12)
    at getOutputOptionsAndPluginDriver (file:///Volumes/D/khanakia/Downloads/thewildai_chatbot_bubble/node_modules/.pnpm/rollup@4.34.1/node_modules/rollup/dist/es/shared/node-entry.js:22801:19)
    at handleGenerateWrite (file:///Volumes/D/khanakia/Downloads/thewildai_chatbot_bubble/node_modules/.pnpm/rollup@4.34.1/node_modules/rollup/dist/es/shared/node-entry.js:22777:74)
    at buildEnvironment (file:///Volumes/D/khanakia/Downloads/thewildai_chatbot_bubble/node_modules/.pnpm/vite@6.0.11_terser@5.37.0/node_modules/vite/dist/node/chunks/dep-M1IYMR16.js:51082:16)
    at Object.defaultBuildApp [as buildApp] (file:///Volumes/D/khanakia/Downloads/thewildai_chatbot_bubble/node_modules/.pnpm/vite@6.0.11_terser@5.37.0/node_modules/vite/dist/node/chunks/dep-M1IYMR16.js:51513:5)
    at CAC.<anonymous> (file:///Volumes/D/khanakia/Downloads/thewildai_chatbot_bubble/node_modules/.pnpm/vite@6.0.11_terser@5.37.0/node_modules/vite/dist/node/cli.js:853:7)
 ELIFECYCLE  Command failed with exit code 1.

```

**Comment by leafoflegend** [comment]
Pretty much makes this library unusable. `library` mode, nothing else special.

```
Invalid value for option "output.manualChunks" - this option is not supported for "output.inlineDynamicImports".
    at getRollupError (file:///Users/eszwajkowski/Code/swiss_cheese/node_modules/vite/node_modules/rollup/dist/es/shared/parseAst.js:397:41)
    at error (file:///Users/eszwajkowski/Code/swiss_cheese/node_modules/vite/node_modules/rollup/dist/es/shared/parseAst.js:393:42)
    at getManualChunks (file:///Users/eszwajkowski/Code/swiss_cheese/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:22949:20)
    at normalizeOutputOptions (file:///Users/eszwajkowski/Code/swiss_cheese/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:22737:23)
    at getOutputOptions (file:///Users/eszwajkowski/Code/swiss_cheese/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:23124:12)
    at getOutputOptionsAndPluginDriver (file:///Users/eszwajkowski/Code/swiss_cheese/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:23119:19)
    at handleGenerateWrite (file:///Users/eszwajkowski/Code/swiss_cheese/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:23095:74)
    at build (file:///Users/eszwajkowski/Code/swiss_cheese/node_modules/vite/dist/node/chunks/dep-DbT5NFX0.js:65649:16)
    at cheesecloth (file:///Users/eszwajkowski/Code/swiss_cheese/node_modules/@web-ib/cheesecloth/js/src/cheesecloth.js:112:13)
    at Command.<anonymous> (file:///Users/eszwajkowski/Code/swiss_cheese/node_modules/@web-ib/cheesecloth/js/src/script.js:212:5)
```

**Comment by z0ffy** [comment]
Already supported https://github.com/z0ffy/vite-plugin-bundle-obfuscator/pull/209
